In [1]:
import numpy as np 

# Creating Arrays

#### 1D array

In [2]:
np.array([1,2,3])

array([1, 2, 3])

#### 2D array

In [3]:
np.array([(1,2,3), (4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

#### 1D array of length 2 having 0s.

In [4]:
np.zeros(2)

array([0., 0.])

#### 2D array of length 2*3 having 0s.

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#### 1D array of length 2 having 1s.

In [6]:
np.ones(2)

array([1., 1.])

#### 2D array of length 2*3 having 1s.

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Identical matrix

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Array of 6 evenly divided values from 0 to 100

In [9]:
np.linspace(1, 100, 6)

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

#### Array of 5 evenly divided values from 0 to 5

In [10]:
np.linspace(1,50, 5)
#exactly like 5 number theory 

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

#### Arrange 

> syntax:

> np.arange(start, end, range to jump)
- Array of values from 0 to less than 100 with step 10

In [11]:
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

#### 2x3 array with all values 8

In [12]:
np.full((2,3), 8)

array([[8, 8, 8],
       [8, 8, 8]])

#### Random flaoting values 
> 2*3 array of random floats between 0-100

In [13]:
np.random.rand(2,3)*10

array([[6.00785212, 9.36193217, 9.45855705],
       [5.97681023, 0.62687359, 9.64385263]])

#### Random flaoting values 
> 2*3 array of random int val from 0 to given range

In [14]:
np.random.randint(5, size= (2,3))

array([[0, 4, 3],
       [0, 2, 1]])

# Inspecting Properties 

In [15]:
arr= np.random.rand(2,3)*10

In [16]:
arr

array([[6.81163136, 7.98830059, 0.89370917],
       [3.32744691, 2.04141097, 3.91136214]])

####  Returns number of elements in arr

In [17]:
arr.size

6

####  Returns dimensions of arr

In [18]:
arr.shape

(2, 3)

#### Return type of ele of arr

In [19]:
arr.dtype

dtype('float64')

#### Convert arr elements to dtype

In [20]:
arr= arr.astype('int64')

In [21]:
arr

array([[6, 7, 0],
       [3, 2, 3]])

####  Convert arr to a Python list

In [22]:
arr.tolist()

[[6, 7, 0], [3, 2, 3]]

#### View documentation for any method of np

In [23]:
np.info(np.shape)

Return the shape of an array.

Parameters
----------
a : array_like
    Input array.

Returns
-------
shape : tuple of ints
    The elements of the shape tuple give the lengths of the
    corresponding array dimensions.

See Also
--------
len : ``len(a)`` is equivalent to ``np.shape(a)[0]`` for N-D arrays with
      ``N>=1``.
ndarray.shape : Equivalent array method.

Examples
--------
>>> np.shape(np.eye(3))
(3, 3)
>>> np.shape([[1, 3]])
(1, 2)
>>> np.shape([0])
(1,)
>>> np.shape(0)
()

>>> a = np.array([(1, 2), (3, 4), (5, 6)],
...              dtype=[('x', 'i4'), ('y', 'i4')])
>>> np.shape(a)
(3,)
>>> a.shape
(3,)


# Copying/ Sorting/ Reshaping 

#### Copies arr to new memory

In [24]:
array = np.copy(arr)

In [25]:
array

array([[6, 7, 0],
       [3, 2, 3]])

#### Creates view of arr elements with dtype

In [26]:
array.view('float64')

array([[3.0e-323, 3.5e-323, 0.0e+000],
       [1.5e-323, 9.9e-324, 1.5e-323]])

In [27]:
print(array)

[[6 7 0]
 [3 2 3]]


#### Transpose of array

In [28]:
array.T

array([[6, 3],
       [7, 2],
       [0, 3]])

In [29]:
array.shape

(2, 3)

#### Reshapes array to 3 rows, 2 columns without changing data

In [30]:
array.reshape(3,2)

array([[6, 7],
       [0, 3],
       [2, 3]])

#### Changes array shape to m*n & fill new val with 0s

In [31]:
array.resize((5, 4), refcheck=False)


In [32]:
array

array([[6, 7, 0, 3],
       [2, 3, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Adding/ Removing elements 

In [33]:
arr

array([[6, 7, 0],
       [3, 2, 3]])

#### Appends values to end of arr

In [34]:
values = [1,2,3,4,5,6,6,7,8,9,0,2,3,5]
array = np.append(arr,values)

In [35]:
array

array([6, 7, 0, 3, 2, 3, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 0, 2, 3, 5])

####  Inserts values into array before index n

In [36]:
np.insert(array, 2, values)

array([6, 7, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 0, 2, 3, 5, 0, 3, 2, 3, 1, 2,
       3, 4, 5, 6, 6, 7, 8, 9, 0, 2, 3, 5])

####  Deletes row on index n of array

In [37]:
array = np.delete(arr,1,axis=0)
array

array([[6, 7, 0]])

#### Deletes column on index n of array

In [38]:
np.delete(arr,2,axis=1)

array([[6, 7],
       [3, 2]])

# Combining/ Splitting

In [39]:
arr1 = np.array([(0,1,2), (3,4,5)])
arr2 = np.array([(6,7,8), (9,10, 0)])

In [40]:
print("arr1: ")
arr1

arr1: 


array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
print("arr2: ")
arr2

arr2: 


array([[ 6,  7,  8],
       [ 9, 10,  0]])

#### Adds arr2 as rows to the end of arr1

In [42]:
np.concatenate((arr1, arr2), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10,  0]])

#### Adds arr2 as columns to end of arr1

In [43]:
np.concatenate((arr1, arr2), axis=1)


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10,  0]])

#### Splits arr into *nth* sub-arrays

In [44]:
arr = arr1

In [45]:
arr1, arr2 = np.split(arr,2) # n=2

In [46]:
arr1

array([[0, 1, 2]])

In [47]:
arr2

array([[3, 4, 5]])

####  Splits arr horizontally on the *nth* index

In [48]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
arr1, arr2, arr3 = np.hsplit(arr,3) #n=3

In [50]:
print(f"Arr1= {arr1}\nArr2= {arr2}\nArr3= {arr3}")

Arr1= [[0]
 [3]]
Arr2= [[1]
 [4]]
Arr3= [[2]
 [5]]


# Indexing/ Slicing/ Subsetting

#### 1D aar indexing

In [51]:
arr= np.array((1,2,3))

In [52]:
arr

array([1, 2, 3])

In [53]:
arr[2]

3

#### Assigns arr ele on index *nth* 

In [54]:
arr[2] = 4

In [55]:
arr

array([1, 2, 4])

#### Returns the ele at indices 0-n (n excluded) 

In [56]:
arr[0:2]

array([1, 2])

#### 2D arr indexing

In [57]:
arr = np.array([(1,2,3),(4,5,6)])

In [58]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr[1,2] # row, col

6

#### Assigns array element on index m*n

In [60]:
arr[1,2] = 10

In [61]:
arr

array([[ 1,  2,  3],
       [ 4,  5, 10]])

#### Returns the ele at indices 0-n (n excluded) at m

In [62]:
arr[0:2,2] # n=2, col=2

array([ 3, 10])

In [63]:
arr[0:1]

array([[1, 2, 3]])

#### Returns an array with boolean values

In [64]:
arr_bool = arr<2

In [65]:
arr_bool

array([[ True, False, False],
       [False, False, False]])

In [66]:
(arr<11) & (arr>-1) # range from -1 to 11

array([[ True,  True,  True],
       [ True,  True,  True]])

In [67]:
arr_bool

array([[ True, False, False],
       [False, False, False]])

####  Inverts a boolean array

In [68]:
~arr_bool

array([[False,  True,  True],
       [ True,  True,  True]])

####  Returns arr elem < or > n

In [69]:
arr

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [70]:
arr[arr<5]

array([1, 2, 3, 4])

In [71]:
arr[arr>2]

array([ 3,  4,  5, 10])

# Scalar Math

In [72]:
arr

array([[ 1,  2,  3],
       [ 4,  5, 10]])

#### Add n to each arr ele

In [73]:
np.add(arr,1) # n=1

array([[ 2,  3,  4],
       [ 5,  6, 11]])

#### subtarct n to each arr ele

In [74]:
np.subtract(arr,2) # n=2

array([[-1,  0,  1],
       [ 2,  3,  8]])

#### Multiply n to each arr ele

In [75]:
np.multiply(arr, 3) # n=3

array([[ 3,  6,  9],
       [12, 15, 30]])

#### Divide n to each arr ele

In [76]:
np.divide(arr, 2)

array([[0.5, 1. , 1.5],
       [2. , 2.5, 5. ]])

#### power of n to each arr ele

In [77]:
np.power(arr, 3)# n=3

array([[   1,    8,   27],
       [  64,  125, 1000]])

# Vector Math

In [78]:
arr1 = np.array([(1,2,3), (4,5,6)])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
arr2 = np.array([(4,5,6), (7,8,9)])
arr2

array([[4, 5, 6],
       [7, 8, 9]])

#### Vectors Addition

In [80]:
np.add(arr1, arr2)

array([[ 5,  7,  9],
       [11, 13, 15]])

#### Vectors Subtraction 

In [81]:
np.subtract(arr2, arr1)

array([[3, 3, 3],
       [3, 3, 3]])

#### Vectors Multiplication 

In [82]:
np.multiply(arr1, arr2)

array([[ 4, 10, 18],
       [28, 40, 54]])

#### Vectors Division 

In [83]:
np.divide(arr2, arr1)

array([[4.  , 2.5 , 2.  ],
       [1.75, 1.6 , 1.5 ]])

#### Vectors Power 

In [84]:
np.power(arr1, arr2)

array([[       1,       32,      729],
       [   16384,   390625, 10077696]])

#### Array Equal

>  Returns True if the arr have the same ele and shape

In [85]:
np.array_equal(arr1,arr2)

False

In [86]:
arr

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [87]:
arr = np.array([(1,2,3),(4,5,6)])
arr

array([[1, 2, 3],
       [4, 5, 6]])

#### log of each ele

In [88]:
np.log(arr)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

#### Sqrt of each ele in the arr

In [89]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

#### sin of each ele

In [90]:
arr = np.sin(arr)
arr

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

#### Absolute of each ele in arr

In [91]:
arr = np.abs(arr)
arr

array([[0.84147098, 0.90929743, 0.14112001],
       [0.7568025 , 0.95892427, 0.2794155 ]])

#### Ceil 

> Rounds up to the nearest int

In [92]:
np.ceil(arr)

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Floor

> Rounds down to the nearest int

In [93]:
np.floor(arr)

array([[0., 0., 0.],
       [0., 0., 0.]])

#### Round

> Rounds to the nearest int

In [94]:
np.round(arr)

array([[1., 1., 0.],
       [1., 1., 0.]])

# Statistics

In [95]:
arr = np.array([(1,2,3),(4,5,6)])
arr

array([[1, 2, 3],
       [4, 5, 6]])

#### Mean

> Returns mean along specific axis

In [96]:
np.mean(arr, axis=0)

array([2.5, 3.5, 4.5])

In [97]:
np.mean(arr, axis=1)

array([2., 5.])

#### Sum

> Returns sum of arr

In [98]:
arr.sum()

21

### Min

In [99]:
arr.min()

1

#### Max

In [100]:
arr.max(axis=0)

array([4, 5, 6])

#### Variance

> Returns the variance of specific axis

In [101]:
np.var(arr, axis=0)

array([2.25, 2.25, 2.25])

#### Standard Deviation

> Returns the standard deviation of specific axis

In [102]:
np.std(arr, axis=1)

array([0.81649658, 0.81649658])

#### Correlation

> Returns correlation coefficient of array

In [103]:
np.corrcoef(arr) 

array([[1., 1.],
       [1., 1.]])